/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.util.ArrayList;
import logic.Formula;

/**
 * Interfaz grafica para explicar pasos
 *
 * @author xJoni
 * @version 1.0
 */
public class PrefixFormula extends javax.swing.JFrame {

    /**
     * Creates new form Tree
     *
     * @param prefixFormula
     * @param formulas
     */
    public PrefixFormula(String prefixFormula, ArrayList<Formula> formulas) {
        initComponents();
        txtPrefixFormula.setText(prefixFormula);
        showSteps(formulas);
    }

    private void showSteps(ArrayList<Formula> formulas) {

        String steps = "";
        String formula = "";

        for (int i = 0; i < formulas.size(); i++) {

            if (formulas.get(i).isIsOperator()) {
                switch (formulas.get(i).getOrientation()) {
                    case -1:
                        steps += "";
                        break;
                    case 0:
                        steps += "Continuamos a la izquierda. ";
                        break;
                    case 1:
                        steps += "Continuamos a la derecha. ";
                        break;
                    default:
                        break;
                }

                steps += "De la formula " + formulas.get(i).getText() + "\nObtenemos el operador principal ";
                steps += " [[ " + formulas.get(i).getValue() + " ]] \n";
                formula += formulas.get(i).getValue();
                steps += "Con esto tenemos que nuestra formula en prefijo va asi: " + formula + " \n\n";
            } else {
                switch (formulas.get(i).getOrientation()) {
                    case -1:
                        steps += "Tomamos el atomo negado ";
                        break;
                    case 0:
                        steps += "Tomamos el atomo ubicado a la izquierda ";
                        break;
                    case 1:
                        steps += "Tomamos el atomo ubicado a la derecha ";
                        break;
                    default:
                        break;
                }
                steps += " [[ " + formulas.get(i).getValue() + " ]] \n";
                formula += formulas.get(i).getValue();
                steps += "Con esto tenemos que nuestra formula en prefijo va asi " + formula + " \n\n";
            }
        }

        txtArea.setText(steps);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrefixFormula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pasos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Prefija:");

        txtPrefixFormula.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrefixFormula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPrefixFormula))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtPrefixFormula;
    // End of variables declaration//GEN-END:variables
}
